name: "fitbit_analytics"
version: "1.0.0"
config-version: 2

profile: "fitbit_analytics"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  fitbit_analytics:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
